services:
  - type: web
    name: Stellar Excursions # the name of this service, you should change this
    env: ruby # this app is written in ruby
    plan: free # make sure to set this to free or you'll get billed $$$
    buildCommand: "./bin/render-build.sh" # we already created these two files for you
    startCommand: "./bin/render-start.sh"
    envVars: # this section sets some ENV variables needed by Render for deployment
      - key: NASAAPIKEY
        value: knbdV0LUnOAHdFOj8eulaC0yqk0sDYFe1k2ldK8L

        #generateValue: true
